name = "familia-arbol"
compatibility_date = "2026-05-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "familia_arbol"
database_id = "REEMPLAZA_CON_EL_ID_DE_TU_BASE_D1"
