name = "familia-arbol"
compatibility_date = "2026-05-29"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "familia_arbol"
database_id = "2c5cc428-d4da-408a-b82f-d7601f8ff7a9"
